spring:
  config:
    import: optional:configserver:http://localhost:8888

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}  # 환경 변수나 기본값으로 local profile 사용

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true