services:
  eureka-server:
    container_name: eureka-server-container
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - budgetmate-compose
    depends_on:
      mysql:
        condition: service_healthy

  config-server:
    container_name: config-server-container
    build:
      context: ./config-server
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 5s
      timeout: 3s
      retries: 5
    depends_on:
      eureka-server:
        condition: service_healthy
    volumes:
      - ./config-server-application.yml:/app/config/application.yml
    networks:
      - budgetmate-compose

  gateway:
    container_name: gateway-container
    build:
      context: ./gateway
    ports:
      - "8090:8090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090"]
      interval: 5s
      timeout: 3s
      retries: 5
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - budgetmate-compose

  user-service:
    container_name: user-service-container
    build:
      context: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=user-docker
    networks:
      - budgetmate-compose

  receipt-service:
    container_name: receipt-service-container
    build:
      context: ./receipt-service
    ports:
      - "8082:8082"
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=receipt-docker
    networks:
      - budgetmate-compose

  statis-service:
    container_name: statis-service-container
    build:
      context: ./statis-service
    ports:
      - "8083:8083"
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=statis-docker
    networks:
      - budgetmate-compose

  history-service:
    container_name: history-service-container
    build:
      context: ./history-service
    ports:
      - "8084:8084"
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=history-docker
    networks:
      - budgetmate-compose

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: budget_db
      MYSQL_USER: budget_user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - budgetmate-compose
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  budgetmate-compose:
    external: true

