#spring:
#  application:
#    name:
#      gateway
#server:
#  port:
#    8080
#logging:
#  level:
#    org.springframework: DEBUG

# GatewayApplication.java
#server:
#  port: 8080
#
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/user/**

server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      forward-headers-strategy: framework
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            #- StripPrefix=1
            - PreserveHostHeader
      default-filters:
        - RemoveRequestHeader=Cookie

    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway.filter: DEBUG
    org.springframework.security: DEBUG
    com.budgetmate.user.security: DEBUG
    org.springframework.web: DEBUG
