spring:
  application:
    name: history-service
  profiles:
    active: history-dev
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true



