spring:
  application:
    name: history-service
  profiles:
    active: history-docker
  config:
    import: optional:configserver:http://config-server-container:8888
    #import: optional:configserver:http://localhost:8888
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true



