spring:
  application:
    name: user-service
  profiles:
    active: user-lan-dev
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

