spring:
  config:
    import: optional:configserver:http://localhost:8888

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:lan}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
